version: '3'
services:
  postgres:
    image: postgres
    volumes:
      - ./create-table.sql:/docker-entrypoint-initdb.d/create-table.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: managementuser
    ports:
      - 5433:5432
